package modelo;

public enum TipoHabilidadMagia {
    MONSTRUO_RENACIDO,
    AGUJERO_NEGRO,
    TIFON_ESPACIO_MISTICO,
    ESPADAS_LUZ_REVELADORA,
    OLLA_CODICIA,
    ENTIERRO_INSENSATO,
    RAIGEKI,
    MIL_CUCHILLOS,
    UNIDAD,
    POLIMERIZACION
}
