package src;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        botonCerrar = new javax.swing.JButton();
        botonOpcion1 = new javax.swing.JButton();
        botonOpcion2 = new javax.swing.JButton();
        etiquetaDeInputMultifuncion = new javax.swing.JLabel();
        inputMultifuncion = new javax.swing.JTextField();
        etiquetaMultifuncion = new javax.swing.JLabel();
        scrollCementerio = new javax.swing.JScrollPane();
        tablaCementerio = new javax.swing.JTable();
        scrollMano = new javax.swing.JScrollPane();
        tablaMano = new javax.swing.JTable();
        etiquetaCementerio = new javax.swing.JLabel();
        etiquetaMano = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        contenedorDeCards = new javax.swing.JPanel();
        cardInicio = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        ingresoNombreJugador1 = new javax.swing.JTextField();
        ingresoNombreJugador1.setOpaque(false);
        ingresoNombreJugador1.setBackground(new java.awt.Color(0,0,0,0));
        etiquetaJugador1 = new javax.swing.JLabel();
        ingresoNombreJugador2 = new javax.swing.JTextField();
        ingresoNombreJugador2.setOpaque(false);
        ingresoNombreJugador2.setBackground(new java.awt.Color(0,0,0,0));
        etiquetaJugador2 = new javax.swing.JLabel();
        logoInicio = new javax.swing.JLabel();
        fondoInicio = new javax.swing.JLabel();
        cardDesarrollo = new javax.swing.JPanel();
        botonAtacar = new javax.swing.JButton();
        botonCambiarPosicionDeCarta = new javax.swing.JButton();
        botonCambiarPosicionDeMagia = new javax.swing.JButton();
        botonCambiarPosicionDeMonstruo = new javax.swing.JButton();
        etiquetaDivisoraDelCampo = new javax.swing.JLabel();
        magiaOTrampa0Jugador2EnCampo = new javax.swing.JLabel();
        magiaOTrampa1Jugador2EnCampo = new javax.swing.JLabel();
        magiaOTrampa2Jugador2EnCampo = new javax.swing.JLabel();
        magiaOTrampa3Jugador2EnCampo = new javax.swing.JLabel();
        magiaOTrampa4Jugador2EnCampo = new javax.swing.JLabel();
        monstruo4Jugador2EnCampo = new javax.swing.JLabel();
        monstruo3Jugador2EnCampo = new javax.swing.JLabel();
        monstruo2Jugador2EnCampo = new javax.swing.JLabel();
        monstruo1Jugador2EnCampo = new javax.swing.JLabel();
        monstruo0Jugador2EnCampo = new javax.swing.JLabel();
        botonTerminarMainPhase1 = new javax.swing.JButton();
        botonTerminarBattlePhase = new javax.swing.JButton();
        botonTerminarMainPhase2 = new javax.swing.JButton();
        botonSaltarMainPhase1 = new javax.swing.JButton();
        botonSaltarBattlePhase = new javax.swing.JButton();
        botonSaltarMainPhase2 = new javax.swing.JButton();
        botonPonerCarta = new javax.swing.JButton();
        botonPonerTrampa = new javax.swing.JButton();
        botonPonerMagia = new javax.swing.JButton();
        botonPonerMagiaSinUsar = new javax.swing.JButton();
        botonPonerMagiaUsandola = new javax.swing.JButton();
        botonPonerMonstruo = new javax.swing.JButton();
        botonPonerMonstruoEnDefensa = new javax.swing.JButton();
        botonPonerMonstruoEnAtaque = new javax.swing.JButton();
        monstruo0Jugador1EnCampo = new javax.swing.JLabel();
        monstruo1Jugador1EnCampo = new javax.swing.JLabel();
        monstruo2Jugador1EnCampo = new javax.swing.JLabel();
        monstruo3Jugador1EnCampo = new javax.swing.JLabel();
        monstruo4Jugador1EnCampo = new javax.swing.JLabel();
        magiaOTrampa4Jugador1EnCampo = new javax.swing.JLabel();
        magiaOTrampa3Jugador1EnCampo = new javax.swing.JLabel();
        magiaOTrampa2Jugador1EnCampo = new javax.swing.JLabel();
        magiaOTrampa1Jugador1EnCampo = new javax.swing.JLabel();
        magiaOTrampa0Jugador1EnCampo = new javax.swing.JLabel();
        etiquetaJugador2EnCampo = new javax.swing.JLabel();
        etiquetaJugador1EnCampo = new javax.swing.JLabel();
        etiquetaFaseEnCurso = new javax.swing.JLabel();
        etiquetaTurnoEnCurso = new javax.swing.JLabel();
        fondoDesarrollo = new javax.swing.JLabel();
        cardFinal = new javax.swing.JPanel();
        botonVolverAJugar = new javax.swing.JButton();
        etiquetaHasGanado = new javax.swing.JLabel();
        fondoFinal = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(null);

        botonCerrar.setBackground(new java.awt.Color(204, 204, 204));
        botonCerrar.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.setVisible(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(botonCerrar);
        botonCerrar.setBounds(420, 280, 70, 21);

        botonOpcion1.setBackground(new java.awt.Color(204, 204, 204));
        botonOpcion1.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        botonOpcion1.setText("Sí");
        botonOpcion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOpcion1.setVisible(false);
        botonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(botonOpcion1);
        botonOpcion1.setBounds(210, 280, 50, 21);

        botonOpcion2.setBackground(new java.awt.Color(204, 204, 204));
        botonOpcion2.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        botonOpcion2.setText("No");
        botonOpcion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOpcion2.setVisible(false);
        botonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(botonOpcion2);
        botonOpcion2.setBounds(290, 280, 50, 21);

        etiquetaDeInputMultifuncion.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        etiquetaDeInputMultifuncion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaDeInputMultifuncion.setText("Etiqueta:");
        etiquetaDeInputMultifuncion.setVisible(false);
        jDialog1.getContentPane().add(etiquetaDeInputMultifuncion);
        etiquetaDeInputMultifuncion.setBounds(10, 280, 90, 17);

        inputMultifuncion.setText("Su texto aquí");
        inputMultifuncion.setVisible(false);
        jDialog1.getContentPane().add(inputMultifuncion);
        inputMultifuncion.setBounds(110, 280, 150, 22);

        etiquetaMultifuncion.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        etiquetaMultifuncion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaMultifuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMultifuncion.setText("Texto Multifunción");
        etiquetaMultifuncion.setVisible(false);
        jDialog1.getContentPane().add(etiquetaMultifuncion);
        etiquetaMultifuncion.setBounds(20, 130, 470, 17);

        scrollCementerio.setVisible(false);

        tablaCementerio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Tipo", "Nombre", "Ataque", "Defensa", "Descripción"
            }
        ));
        scrollCementerio.setViewportView(tablaCementerio);
        if (tablaCementerio.getColumnModel().getColumnCount() > 0) {
            tablaCementerio.getColumnModel().getColumn(0).setPreferredWidth(8);
            tablaCementerio.getColumnModel().getColumn(0).setMaxWidth(8);
            tablaCementerio.getColumnModel().getColumn(1).setPreferredWidth(45);
            tablaCementerio.getColumnModel().getColumn(1).setMaxWidth(45);
            tablaCementerio.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablaCementerio.getColumnModel().getColumn(2).setMaxWidth(150);
            tablaCementerio.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaCementerio.getColumnModel().getColumn(3).setMaxWidth(50);
            tablaCementerio.getColumnModel().getColumn(4).setPreferredWidth(50);
            tablaCementerio.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        jDialog1.getContentPane().add(scrollCementerio);
        scrollCementerio.setBounds(20, 160, 500, 90);

        scrollMano.setVisible(false);

        tablaMano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Tipo", "Nombre", "Ataque", "Defensa", "Descripción"
            }
        ));
        scrollMano.setViewportView(tablaMano);
        if (tablaMano.getColumnModel().getColumnCount() > 0) {
            tablaMano.getColumnModel().getColumn(0).setPreferredWidth(8);
            tablaMano.getColumnModel().getColumn(0).setMaxWidth(8);
            tablaMano.getColumnModel().getColumn(1).setPreferredWidth(45);
            tablaMano.getColumnModel().getColumn(1).setMaxWidth(45);
            tablaMano.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablaMano.getColumnModel().getColumn(2).setMaxWidth(150);
            tablaMano.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaMano.getColumnModel().getColumn(3).setMaxWidth(50);
            tablaMano.getColumnModel().getColumn(4).setPreferredWidth(50);
            tablaMano.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        jDialog1.getContentPane().add(scrollMano);
        scrollMano.setBounds(20, 30, 500, 90);

        etiquetaCementerio.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        etiquetaCementerio.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCementerio.setText("Cementerio:");
        etiquetaCementerio.setVisible(false);
        jDialog1.getContentPane().add(etiquetaCementerio);
        etiquetaCementerio.setBounds(10, 140, 90, 17);

        etiquetaMano.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        etiquetaMano.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaMano.setText("Mano: ");
        etiquetaMano.setVisible(false);
        jDialog1.getContentPane().add(etiquetaMano);
        etiquetaMano.setBounds(10, 10, 90, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yugilogo-convertido-a-600x500-convertido-a-800x700.jpeg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel17);
        jLabel17.setBounds(-120, -140, 800, 810);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yu-Gi-Oh!");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 700));

        contenedorDeCards.setName("PanelPrincipal"); // NOI18N
        contenedorDeCards.setLayout(new java.awt.CardLayout());

        cardInicio.setMaximumSize(new java.awt.Dimension(800, 700));
        cardInicio.setMinimumSize(new java.awt.Dimension(800, 700));
        cardInicio.setName("Inicio"); // NOI18N
        cardInicio.setOpaque(false);
        cardInicio.setLayout(null);

        botonIniciar.setBackground(new java.awt.Color(204, 204, 204));
        botonIniciar.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cardInicio.add(botonIniciar);
        botonIniciar.setBounds(340, 540, 100, 23);

        ingresoNombreJugador1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        ingresoNombreJugador1.setForeground(new java.awt.Color(255, 255, 255));
        ingresoNombreJugador1.setText("Escriba su nombre");
        ingresoNombreJugador1.setBorder(null);
        ingresoNombreJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNombreJugador1ActionPerformed(evt);
            }
        });
        cardInicio.add(ingresoNombreJugador1);
        ingresoNombreJugador1.setBounds(220, 340, 140, 40);

        etiquetaJugador1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        etiquetaJugador1.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaJugador1.setText("Jugador 1:");
        cardInicio.add(etiquetaJugador1);
        etiquetaJugador1.setBounds(110, 280, 110, 24);

        ingresoNombreJugador2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        ingresoNombreJugador2.setForeground(new java.awt.Color(255, 255, 255));
        ingresoNombreJugador2.setText("Escriba su nombre");
        ingresoNombreJugador2.setBorder(null);
        ingresoNombreJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNombreJugador2ActionPerformed(evt);
            }
        });
        cardInicio.add(ingresoNombreJugador2);
        ingresoNombreJugador2.setBounds(220, 270, 140, 40);

        etiquetaJugador2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        etiquetaJugador2.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaJugador2.setText("Jugador 2:");
        cardInicio.add(etiquetaJugador2);
        etiquetaJugador2.setBounds(110, 350, 110, 30);

        logoInicio.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        logoInicio.setForeground(new java.awt.Color(255, 0, 0));
        logoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yugiletras-convertido-a-250x101-removebg-preview.png"))); // NOI18N
        cardInicio.add(logoInicio);
        logoInicio.setBounds(270, 40, 250, 140);

        fondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yugilogo-convertido-a-600x500-convertido-a-800x700.jpeg"))); // NOI18N
        cardInicio.add(fondoInicio);
        fondoInicio.setBounds(0, 0, 800, 700);

        contenedorDeCards.add(cardInicio, "Inicio");
        cardInicio.getAccessibleContext().setAccessibleName("");

        cardDesarrollo.setMaximumSize(new java.awt.Dimension(800, 700));
        cardDesarrollo.setMinimumSize(new java.awt.Dimension(800, 700));
        cardDesarrollo.setOpaque(false);
        cardDesarrollo.setLayout(null);

        botonAtacar.setBackground(new java.awt.Color(204, 204, 204));
        botonAtacar.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonAtacar.setText("Ataque");
        botonAtacar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAtacar.setMaximumSize(new java.awt.Dimension(90, 35));
        botonAtacar.setMinimumSize(new java.awt.Dimension(90, 35));
        botonAtacar.setVisible(false);
        cardDesarrollo.add(botonAtacar);
        botonAtacar.setBounds(310, 610, 70, 23);

        botonCambiarPosicionDeCarta.setBackground(new java.awt.Color(204, 204, 204));
        botonCambiarPosicionDeCarta.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonCambiarPosicionDeCarta.setText("Cambiar posición");
        botonCambiarPosicionDeCarta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCambiarPosicionDeCarta.setMaximumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeCarta.setMinimumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeCarta.setVisible(false);
        botonCambiarPosicionDeCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPosicionDeCartaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonCambiarPosicionDeCarta);
        botonCambiarPosicionDeCarta.setBounds(350, 610, 140, 23);

        botonCambiarPosicionDeMagia.setBackground(new java.awt.Color(204, 204, 204));
        botonCambiarPosicionDeMagia.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonCambiarPosicionDeMagia.setText("Magia");
        botonCambiarPosicionDeMagia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCambiarPosicionDeMagia.setMaximumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeMagia.setMinimumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeMagia.setVisible(false);
        botonCambiarPosicionDeMagia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPosicionDeMagiaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonCambiarPosicionDeMagia);
        botonCambiarPosicionDeMagia.setBounds(440, 610, 60, 23);

        botonCambiarPosicionDeMonstruo.setBackground(new java.awt.Color(204, 204, 204));
        botonCambiarPosicionDeMonstruo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonCambiarPosicionDeMonstruo.setText("Monstruo");
        botonCambiarPosicionDeMonstruo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCambiarPosicionDeMonstruo.setMaximumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeMonstruo.setMinimumSize(new java.awt.Dimension(90, 35));
        botonCambiarPosicionDeMonstruo.setVisible(false);
        botonCambiarPosicionDeMonstruo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPosicionDeMonstruoActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonCambiarPosicionDeMonstruo);
        botonCambiarPosicionDeMonstruo.setBounds(340, 610, 80, 23);

        etiquetaDivisoraDelCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaDivisoraDelCampo.setText("______________________________________________________________________________________________");
        cardDesarrollo.add(etiquetaDivisoraDelCampo);
        etiquetaDivisoraDelCampo.setBounds(20, 300, 760, 30);

        magiaOTrampa0Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa0Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa0Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa0Jugador2EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa0Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa0Jugador2EnCampo);
        magiaOTrampa0Jugador2EnCampo.setBounds(40, 460, 130, 70);

        magiaOTrampa1Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa1Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa1Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa1Jugador2EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa1Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa1Jugador2EnCampo);
        magiaOTrampa1Jugador2EnCampo.setBounds(180, 460, 130, 70);

        magiaOTrampa2Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa2Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa2Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa2Jugador2EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa2Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa2Jugador2EnCampo);
        magiaOTrampa2Jugador2EnCampo.setBounds(320, 460, 130, 70);

        magiaOTrampa3Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa3Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa3Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa3Jugador2EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa3Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa3Jugador2EnCampo);
        magiaOTrampa3Jugador2EnCampo.setBounds(460, 460, 130, 70);

        magiaOTrampa4Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa4Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa4Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa4Jugador2EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa4Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa4Jugador2EnCampo);
        magiaOTrampa4Jugador2EnCampo.setBounds(600, 460, 130, 70);

        monstruo4Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo4Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo4Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo4Jugador2EnCampo.setText("Nombre Monstruo");
        monstruo4Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo4Jugador2EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo4Jugador2EnCampo);
        monstruo4Jugador2EnCampo.setBounds(600, 360, 110, 80);

        monstruo3Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo3Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo3Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo3Jugador2EnCampo.setText("Nombre Monstruo");
        monstruo3Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo3Jugador2EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo3Jugador2EnCampo);
        monstruo3Jugador2EnCampo.setBounds(460, 360, 110, 80);

        monstruo2Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo2Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo2Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo2Jugador2EnCampo.setText("Nombre Monstruo");
        monstruo2Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo2Jugador2EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo2Jugador2EnCampo);
        monstruo2Jugador2EnCampo.setBounds(320, 360, 110, 80);

        monstruo1Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo1Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo1Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo1Jugador2EnCampo.setText("Nombre Monstruo");
        monstruo1Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo1Jugador2EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo1Jugador2EnCampo);
        monstruo1Jugador2EnCampo.setBounds(180, 360, 110, 80);

        monstruo0Jugador2EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo0Jugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo0Jugador2EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo0Jugador2EnCampo.setText("Nombre Monstruo");
        monstruo0Jugador2EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo0Jugador2EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo0Jugador2EnCampo);
        monstruo0Jugador2EnCampo.setBounds(40, 360, 110, 80);

        botonTerminarMainPhase1.setBackground(new java.awt.Color(204, 204, 204));
        botonTerminarMainPhase1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonTerminarMainPhase1.setText("Terminar fase");
        botonTerminarMainPhase1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonTerminarMainPhase1.setMaximumSize(new java.awt.Dimension(90, 35));
        botonTerminarMainPhase1.setMinimumSize(new java.awt.Dimension(90, 35));
        botonTerminarMainPhase1.setVisible(false);
        cardDesarrollo.add(botonTerminarMainPhase1);
        botonTerminarMainPhase1.setBounds(560, 610, 120, 23);

        botonTerminarBattlePhase.setBackground(new java.awt.Color(204, 204, 204));
        botonTerminarBattlePhase.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonTerminarBattlePhase.setText("Terminar fase");
        botonTerminarBattlePhase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonTerminarBattlePhase.setMaximumSize(new java.awt.Dimension(90, 35));
        botonTerminarBattlePhase.setMinimumSize(new java.awt.Dimension(90, 35));
        botonTerminarBattlePhase.setVisible(false);
        cardDesarrollo.add(botonTerminarBattlePhase);
        botonTerminarBattlePhase.setBounds(560, 610, 120, 23);

        botonTerminarMainPhase2.setBackground(new java.awt.Color(204, 204, 204));
        botonTerminarMainPhase2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonTerminarMainPhase2.setText("Terminar fase");
        botonTerminarMainPhase2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonTerminarMainPhase2.setMaximumSize(new java.awt.Dimension(90, 35));
        botonTerminarMainPhase2.setMinimumSize(new java.awt.Dimension(90, 35));
        botonTerminarMainPhase2.setVisible(false);
        cardDesarrollo.add(botonTerminarMainPhase2);
        botonTerminarMainPhase2.setBounds(560, 610, 120, 23);

        botonSaltarMainPhase1.setBackground(new java.awt.Color(204, 204, 204));
        botonSaltarMainPhase1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonSaltarMainPhase1.setText("Saltar fase");
        botonSaltarMainPhase1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSaltarMainPhase1.setMaximumSize(new java.awt.Dimension(90, 35));
        botonSaltarMainPhase1.setMinimumSize(new java.awt.Dimension(90, 35));
        botonSaltarMainPhase1.setVisible(false);
        cardDesarrollo.add(botonSaltarMainPhase1);
        botonSaltarMainPhase1.setBounds(690, 610, 99, 23);

        botonSaltarBattlePhase.setBackground(new java.awt.Color(204, 204, 204));
        botonSaltarBattlePhase.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonSaltarBattlePhase.setText("Saltar fase");
        botonSaltarBattlePhase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSaltarBattlePhase.setMaximumSize(new java.awt.Dimension(90, 35));
        botonSaltarBattlePhase.setMinimumSize(new java.awt.Dimension(90, 35));
        botonSaltarBattlePhase.setVisible(false);
        cardDesarrollo.add(botonSaltarBattlePhase);
        botonSaltarBattlePhase.setBounds(690, 610, 99, 23);

        botonSaltarMainPhase2.setBackground(new java.awt.Color(204, 204, 204));
        botonSaltarMainPhase2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonSaltarMainPhase2.setText("Saltar fase");
        botonSaltarMainPhase2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSaltarMainPhase2.setMaximumSize(new java.awt.Dimension(90, 35));
        botonSaltarMainPhase2.setMinimumSize(new java.awt.Dimension(90, 35));
        botonSaltarMainPhase2.setVisible(false);
        cardDesarrollo.add(botonSaltarMainPhase2);
        botonSaltarMainPhase2.setBounds(690, 610, 99, 23);

        botonPonerCarta.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerCarta.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerCarta.setText("Poner carta");
        botonPonerCarta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerCarta.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerCarta.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerCarta.setVisible(false);
        cardDesarrollo.add(botonPonerCarta);
        botonPonerCarta.setBounds(130, 610, 100, 23);

        botonPonerTrampa.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerTrampa.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerTrampa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerTrampa.setLabel("Trampa");
        botonPonerTrampa.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerTrampa.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerTrampa.setVisible(false);
        botonPonerTrampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerTrampaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerTrampa);
        botonPonerTrampa.setBounds(140, 610, 70, 23);

        botonPonerMagia.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMagia.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMagia.setText("Magia");
        botonPonerMagia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMagia.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMagia.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMagia.setVisible(false);
        botonPonerMagia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMagiaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMagia);
        botonPonerMagia.setBounds(240, 610, 60, 23);

        botonPonerMagiaSinUsar.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMagiaSinUsar.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMagiaSinUsar.setText("Colocar");
        botonPonerMagiaSinUsar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMagiaSinUsar.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMagiaSinUsar.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMagiaSinUsar.setVisible(false);
        botonPonerMagiaSinUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMagiaSinUsarActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMagiaSinUsar);
        botonPonerMagiaSinUsar.setBounds(210, 610, 70, 23);

        botonPonerMagiaUsandola.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMagiaUsandola.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMagiaUsandola.setText("Usar");
        botonPonerMagiaUsandola.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMagiaUsandola.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMagiaUsandola.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMagiaUsandola.setVisible(false);
        botonPonerMagiaUsandola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMagiaUsandolaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMagiaUsandola);
        botonPonerMagiaUsandola.setBounds(290, 610, 70, 23);

        botonPonerMonstruo.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMonstruo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMonstruo.setText("Monstruo");
        botonPonerMonstruo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMonstruo.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruo.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruo.setVisible(false);
        botonPonerMonstruo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMonstruoActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMonstruo);
        botonPonerMonstruo.setBounds(40, 610, 74, 23);

        botonPonerMonstruoEnDefensa.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMonstruoEnDefensa.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMonstruoEnDefensa.setText("Defensa");
        botonPonerMonstruoEnDefensa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMonstruoEnDefensa.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruoEnDefensa.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruoEnDefensa.setVisible(false);
        botonPonerMonstruoEnDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMonstruoEnDefensaActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMonstruoEnDefensa);
        botonPonerMonstruoEnDefensa.setBounds(90, 610, 70, 23);

        botonPonerMonstruoEnAtaque.setBackground(new java.awt.Color(204, 204, 204));
        botonPonerMonstruoEnAtaque.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonPonerMonstruoEnAtaque.setText("Ataque");
        botonPonerMonstruoEnAtaque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPonerMonstruoEnAtaque.setMaximumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruoEnAtaque.setMinimumSize(new java.awt.Dimension(90, 35));
        botonPonerMonstruoEnAtaque.setVisible(false);
        botonPonerMonstruoEnAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPonerMonstruoEnAtaqueActionPerformed(evt);
            }
        });
        cardDesarrollo.add(botonPonerMonstruoEnAtaque);
        botonPonerMonstruoEnAtaque.setBounds(10, 610, 70, 23);

        monstruo0Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo0Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo0Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo0Jugador1EnCampo.setText("Nombre Monstruo");
        monstruo0Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo0Jugador1EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo0Jugador1EnCampo);
        monstruo0Jugador1EnCampo.setBounds(40, 210, 110, 80);

        monstruo1Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo1Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo1Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo1Jugador1EnCampo.setText("Nombre Monstruo");
        monstruo1Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo1Jugador1EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo1Jugador1EnCampo);
        monstruo1Jugador1EnCampo.setBounds(180, 210, 110, 80);

        monstruo2Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo2Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo2Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo2Jugador1EnCampo.setText("Nombre Monstruo");
        monstruo2Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo2Jugador1EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo2Jugador1EnCampo);
        monstruo2Jugador1EnCampo.setBounds(320, 210, 110, 80);

        monstruo3Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo3Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo3Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo3Jugador1EnCampo.setText("Nombre Monstruo");
        monstruo3Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo3Jugador1EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo3Jugador1EnCampo);
        monstruo3Jugador1EnCampo.setBounds(460, 210, 110, 80);

        monstruo4Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        monstruo4Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        monstruo4Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monstruo4Jugador1EnCampo.setText("Nombre Monstruo");
        monstruo4Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        monstruo4Jugador1EnCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        cardDesarrollo.add(monstruo4Jugador1EnCampo);
        monstruo4Jugador1EnCampo.setBounds(600, 210, 110, 80);

        magiaOTrampa4Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa4Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa4Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa4Jugador1EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa4Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa4Jugador1EnCampo);
        magiaOTrampa4Jugador1EnCampo.setBounds(590, 80, 130, 70);

        magiaOTrampa3Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa3Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa3Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa3Jugador1EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa3Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa3Jugador1EnCampo);
        magiaOTrampa3Jugador1EnCampo.setBounds(450, 80, 130, 70);

        magiaOTrampa2Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa2Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa2Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa2Jugador1EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa2Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa2Jugador1EnCampo);
        magiaOTrampa2Jugador1EnCampo.setBounds(310, 80, 130, 70);

        magiaOTrampa1Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa1Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa1Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa1Jugador1EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa1Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa1Jugador1EnCampo);
        magiaOTrampa1Jugador1EnCampo.setBounds(170, 80, 130, 70);

        magiaOTrampa0Jugador1EnCampo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        magiaOTrampa0Jugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        magiaOTrampa0Jugador1EnCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magiaOTrampa0Jugador1EnCampo.setText("NombreMagia/Trampa");
        magiaOTrampa0Jugador1EnCampo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cardDesarrollo.add(magiaOTrampa0Jugador1EnCampo);
        magiaOTrampa0Jugador1EnCampo.setBounds(30, 80, 130, 70);

        etiquetaJugador2EnCampo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        etiquetaJugador2EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaJugador2EnCampo.setText("Jugador 2:");
        cardDesarrollo.add(etiquetaJugador2EnCampo);
        etiquetaJugador2EnCampo.setBounds(40, 550, 100, 19);

        etiquetaJugador1EnCampo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        etiquetaJugador1EnCampo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaJugador1EnCampo.setText("Jugador 1:");
        cardDesarrollo.add(etiquetaJugador1EnCampo);
        etiquetaJugador1EnCampo.setBounds(30, 60, 90, 19);

        etiquetaFaseEnCurso.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        etiquetaFaseEnCurso.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaFaseEnCurso.setText("fase");
        cardDesarrollo.add(etiquetaFaseEnCurso);
        etiquetaFaseEnCurso.setBounds(380, 50, 36, 19);

        etiquetaTurnoEnCurso.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        etiquetaTurnoEnCurso.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTurnoEnCurso.setText("Turno: ");
        cardDesarrollo.add(etiquetaTurnoEnCurso);
        etiquetaTurnoEnCurso.setBounds(20, 20, 51, 19);

        fondoDesarrollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yugilogo-convertido-a-600x500-convertido-a-800x700.jpeg"))); // NOI18N
        cardDesarrollo.add(fondoDesarrollo);
        fondoDesarrollo.setBounds(0, 0, 800, 700);

        contenedorDeCards.add(cardDesarrollo, "ponerCarta");

        cardFinal.setMaximumSize(new java.awt.Dimension(800, 700));
        cardFinal.setMinimumSize(new java.awt.Dimension(800, 700));
        cardFinal.setLayout(null);

        botonVolverAJugar.setBackground(new java.awt.Color(204, 204, 204));
        botonVolverAJugar.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        botonVolverAJugar.setText("Volver A Jugar");
        botonVolverAJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonVolverAJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAJugarActionPerformed(evt);
            }
        });
        cardFinal.add(botonVolverAJugar);
        botonVolverAJugar.setBounds(620, 600, 130, 30);

        etiquetaHasGanado.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        etiquetaHasGanado.setForeground(new java.awt.Color(204, 0, 0));
        etiquetaHasGanado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaHasGanado.setText("FELICIDADES has ganado");
        cardFinal.add(etiquetaHasGanado);
        etiquetaHasGanado.setBounds(40, 180, 720, 240);

        fondoFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yugilogo-convertido-a-600x500-convertido-a-800x700.jpeg"))); // NOI18N
        cardFinal.add(fondoFinal);
        fondoFinal.setBounds(0, 0, 800, 700);

        contenedorDeCards.add(cardFinal, "card4");

        getContentPane().add(contenedorDeCards, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPonerMagiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMagiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMagiaActionPerformed

    private void botonPonerMonstruoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMonstruoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMonstruoActionPerformed

    private void botonPonerTrampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerTrampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerTrampaActionPerformed

    private void ingresoNombreJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNombreJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNombreJugador1ActionPerformed

    private void ingresoNombreJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNombreJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNombreJugador2ActionPerformed

    private void botonVolverAJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverAJugarActionPerformed

    private void botonCambiarPosicionDeMagiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPosicionDeMagiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPosicionDeMagiaActionPerformed

    private void botonCambiarPosicionDeMonstruoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPosicionDeMonstruoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPosicionDeMonstruoActionPerformed

    private void botonCambiarPosicionDeCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPosicionDeCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPosicionDeCartaActionPerformed

    private void botonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOpcion2ActionPerformed

    private void botonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOpcion1ActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonPonerMonstruoEnAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMonstruoEnAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMonstruoEnAtaqueActionPerformed

    private void botonPonerMonstruoEnDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMonstruoEnDefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMonstruoEnDefensaActionPerformed

    private void botonPonerMagiaSinUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMagiaSinUsarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMagiaSinUsarActionPerformed

    private void botonPonerMagiaUsandolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPonerMagiaUsandolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPonerMagiaUsandolaActionPerformed



    //AQUÍ EMPIEZAN LOS METODOS AÑADIDOS PARA REL FLUJO DEL JUEGO

    private void imprimirMonstruo(JLabel etiqueta, Monstruo[] monstruos, byte i, String nombre, byte nivel, short ataque, short defensa){
        if(monstruos[i].isVisible()){
            if(monstruos[i].isEnPosicionAtaque()){
                etiqueta.setText(nombre + "\n" + nivel + "\n" + ataque + "\n" + defensa + "\n" + "En posición  de ataque");
            }
            else{
                etiqueta.setText(nombre + "\n" + nivel + "\n" + ataque + "\n" + defensa + "\n" + "En posición de defensa");
            }
        }
        else{
            etiqueta.setText("Carta no visible");
        }
    }
    private void imprimirMagiasYTrampas(JLabel etiqueta, Carta[] magicasOTrampas, byte i){
        if(magicasOTrampas[i] instanceof Magia){
            etiqueta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        }
        else{
            etiqueta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        }
        if(magicasOTrampas[i].isVisible()){
            etiqueta.setText(magicasOTrampas[i].getNombre() + "\n" + magicasOTrampas[i].getCuadroDeTexto());
        }
        else{
            etiqueta.setText("Carta no visible");
        }
    }
    private void imprimirCampo(Duelo duelo){
        JLabel[] etiquetasMonstruosJugador1 = {monstruo0Jugador1EnCampo, monstruo1Jugador1EnCampo, monstruo2Jugador1EnCampo, monstruo3Jugador1EnCampo, monstruo4Jugador1EnCampo};
        JLabel[] etiquetasMonstruosJugador2 = {monstruo0Jugador2EnCampo, monstruo1Jugador2EnCampo, monstruo2Jugador2EnCampo, monstruo3Jugador2EnCampo, monstruo4Jugador2EnCampo};
        JLabel[] etiquetasMagiasYTrampasJugador1 = {magiaOTrampa0Jugador1EnCampo, magiaOTrampa1Jugador1EnCampo, magiaOTrampa2Jugador1EnCampo, magiaOTrampa3Jugador1EnCampo, magiaOTrampa4Jugador1EnCampo};
        JLabel[] etiquetasMagiasYTrampasJugador2 = {magiaOTrampa0Jugador2EnCampo, magiaOTrampa1Jugador2EnCampo, magiaOTrampa2Jugador2EnCampo, magiaOTrampa3Jugador2EnCampo, magiaOTrampa4Jugador2EnCampo};
        etiquetaJugador1EnCampo.setText(duelo.getCampo().getJugador1().getNombre() + ": ❤ " + duelo.getCampo().getJugador1().getLP() + " LP");
        etiquetaJugador2EnCampo.setText(duelo.getCampo().getJugador2().getNombre() + ": ❤ " + duelo.getCampo().getJugador2().getLP() + " LP");
        etiquetaTurnoEnCurso.setText("Turno: " + duelo.getTurno());
        etiquetaFaseEnCurso.setText(duelo.getFase());
        for(int i=0; i<5; i++){
            if(duelo.getCampo().getMonstruosEnCampoJugador1()[i] != null){
                String nombre = duelo.getCampo().getMonstruosEnCampoJugador1()[i].getNombre();
                byte nivel = duelo.getCampo().getMonstruosEnCampoJugador1()[i].getNivel();
                short ataque = duelo.getCampo().getMonstruosEnCampoJugador1()[i].getAtaque();
                short defensa = duelo.getCampo().getMonstruosEnCampoJugador1()[i].getDefensa();
                imprimirMonstruo(etiquetasMonstruosJugador1[i], duelo.getCampo().getMonstruosEnCampoJugador1(),(byte) i, nombre, nivel, ataque, defensa);
            }
            else{
                etiquetasMonstruosJugador1[i].setText("Posición vacía");
            }
            if(duelo.getCampo().getMagicasYTrampasEnCampoJugador1()[i] != null){
                imprimirMagiasYTrampas(etiquetasMagiasYTrampasJugador1[i], duelo.getCampo().getMagicasYTrampasEnCampoJugador1(), (byte) i);
            }
            else{
                etiquetasMagiasYTrampasJugador1[i].setText("Posición vacía");
            }
            if(duelo.getCampo().getMonstruosEnCampoJugador2()[i] != null){
                String nombre = duelo.getCampo().getMonstruosEnCampoJugador2()[i].getNombre();
                byte nivel = duelo.getCampo().getMonstruosEnCampoJugador2()[i].getNivel();
                short ataque = duelo.getCampo().getMonstruosEnCampoJugador2()[i].getAtaque();
                short defensa = duelo.getCampo().getMonstruosEnCampoJugador2()[i].getDefensa();
                imprimirMonstruo(etiquetasMonstruosJugador2[i], duelo.getCampo().getMonstruosEnCampoJugador2(), (byte) i, nombre, nivel, ataque, defensa);
            }
            else{
                etiquetasMonstruosJugador2[i].setText("Posición vacía");
            }
            if(duelo.getCampo().getMagicasYTrampasEnCampoJugador2()[i] != null){
                imprimirMagiasYTrampas(etiquetasMagiasYTrampasJugador2[i], duelo.getCampo().getMagicasYTrampasEnCampoJugador2(), (byte) i);
            }
            else{
                etiquetasMagiasYTrampasJugador2[i].setText("Posición vacía");
            }
        }
    }

    private void resetearDialogWindow() {
        etiquetaMano.setVisible(false);
        etiquetaMano.setText("Mano: ");
        etiquetaCementerio.setVisible(false);
        scrollMano.setVisible(false);
        scrollCementerio.setVisible(false);
        etiquetaMultifuncion.setVisible(false);
        inputMultifuncion.setVisible(false);
        etiquetaDeInputMultifuncion.setVisible(false);
        botonCerrar.setVisible(false);
        botonOpcion1.setVisible(false);
        botonOpcion2.setVisible(false);
    }
    private void imprimirMano(Jugador jugador){
        DefaultTableModel modelo = (DefaultTableModel) tablaMano.getModel();
        modelo.setRowCount(0);
        byte i = 0;
        for (Carta carta : jugador.getMano()) {
            String tipo = "", ataque = "", defensa = "", descripcion = carta.getCuadroDeTexto();
            if (carta instanceof Monstruo) {
                tipo = "MON";
                Monstruo m = (Monstruo) carta;
                ataque = String.valueOf(m.getAtaque());
                defensa = String.valueOf(m.getDefensa());
            } else if (carta instanceof Magia) {
                tipo = "MAG";
            } else if (carta instanceof Trampa) {
                tipo = "TRA";
            }
            
            modelo.addRow(new Object[]{i, tipo, carta.getNombre(), ataque, defensa, descripcion});
            i++;
        }
    }
    private void imprimirCementerio(Jugador jugador){
        DefaultTableModel modelo = (DefaultTableModel) tablaCementerio.getModel();
        modelo.setRowCount(0);
        byte i = 0;
        for (Carta carta : jugador.getCementerio()) {
            String tipo = "", ataque = "", defensa = "", descripcion = carta.getCuadroDeTexto();
            if (carta instanceof Monstruo) {
                tipo = "MON";
                Monstruo m = (Monstruo) carta;
                ataque = String.valueOf(m.getAtaque());
                defensa = String.valueOf(m.getDefensa());
            } else if (carta instanceof Magia) {
                tipo = "MAG";
            } else if (carta instanceof Trampa) {
                tipo = "TRA";
            }
            
            modelo.addRow(new Object[]{i, tipo, carta.getNombre(), ataque, defensa, descripcion});
            i++;
        }
    }
    private void imprimirMazo(Jugador jugador){
        DefaultTableModel modelo = (DefaultTableModel) tablaMano.getModel();
        modelo.setRowCount(0);
        byte i = 0;
        for (Carta carta : jugador.getMazo()) {
            String tipo = "", ataque = "", defensa = "", descripcion = carta.getCuadroDeTexto();
            if (carta instanceof Monstruo) {
                tipo = "MON";
                Monstruo m = (Monstruo) carta;
                ataque = String.valueOf(m.getAtaque());
                defensa = String.valueOf(m.getDefensa());
            } else if (carta instanceof Magia) {
                tipo = "MAG";
            } else if (carta instanceof Trampa) {
                tipo = "TRA";
            }
            
            modelo.addRow(new Object[]{i, tipo, carta.getNombre(), ataque, defensa, descripcion});
            i++;
        }
    }
    private void imprimirManoYCementerioAtacante(Duelo duelo){
        resetearDialogWindow();
        jDialog1.setTitle("Mano Y Cementerio");
        Jugador atacante;
        if(duelo.getTurno()%2==0){
            atacante = duelo.getCampo().getJugador1();
        }
        else{
            atacante = duelo.getCampo().getJugador2();
        }
        etiquetaMano.setVisible(true);
        etiquetaCementerio.setVisible(true);
        scrollMano.setVisible(true);
        scrollCementerio.setVisible(true);
        imprimirMano(atacante);
        imprimirCementerio(atacante);
    }
    private void imprimirManoYCementerioAtacanteYCementerioDefensor(Duelo duelo){
        resetearDialogWindow();
        jDialog1.setTitle("Mano Y Cementerio");
        Jugador atacante, defensor;
        if(duelo.getTurno()%2==0){
            atacante = duelo.getCampo().getJugador1();
            defensor = duelo.getCampo().getJugador2();
        }
        else{
            atacante = duelo.getCampo().getJugador2();
            defensor = duelo.getCampo().getJugador1();
        }
        etiquetaMano.setVisible(true);
        etiquetaCementerio.setVisible(true);
        scrollMano.setVisible(true);
        scrollCementerio.setVisible(true);
        imprimirMano(atacante);
        imprimirCementerio(atacante);
        DefaultTableModel modelo = (DefaultTableModel) tablaCementerio.getModel();
        byte i = 0;
        for (Carta carta : defensor.getCementerio()) {
            String tipo = "", ataque = "", defensa = "", descripcion = carta.getCuadroDeTexto();
            if (carta instanceof Monstruo) {
                tipo = "MON";
                Monstruo m = (Monstruo) carta;
                ataque = String.valueOf(m.getAtaque());
                defensa = String.valueOf(m.getDefensa());
            } else if (carta instanceof Magia) {
                tipo = "MAG";
            } else if (carta instanceof Trampa) {
                tipo = "TRA";
            }
            
            modelo.addRow(new Object[]{i, tipo, carta.getNombre(), ataque, defensa, descripcion});
            i++;
        }
    }
    private void imprimirMazo(Duelo duelo, Jugador jugador){
        resetearDialogWindow();
        jDialog1.setTitle("Mazo");
        etiquetaMano.setText("Mazo: ");
        scrollMano.setVisible(true);
        etiquetaMano.setVisible(true);
        imprimirMazo(jugador);
    }

    private void setearNombresDeJugadores(Duelo duelo){ 
        String nombreJugador1 = ingresoNombreJugador1.getText().trim(); 
        String nombreJugador2 = ingresoNombreJugador2.getText().trim(); 
        if (nombreJugador1.isEmpty() || nombreJugador2.isEmpty()){ 
            javax.swing.JOptionPane.showMessageDialog(this, "Ambos nombres son obligatorios"); 
            return; 
        }
        else{
            duelo.getCampo().getJugador1().setNombre(nombreJugador1);
            duelo.getCampo().getJugador2().setNombre(nombreJugador2);
        }
    }

    //AQUÍ TERMINAN LOS METODOS AÑADIDOS PARA EL FLUJO DEL JUEGO



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtacar;
    private javax.swing.JButton botonCambiarPosicionDeCarta;
    private javax.swing.JButton botonCambiarPosicionDeMagia;
    private javax.swing.JButton botonCambiarPosicionDeMonstruo;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonOpcion1;
    private javax.swing.JButton botonOpcion2;
    private javax.swing.JButton botonPonerCarta;
    private javax.swing.JButton botonPonerMagia;
    private javax.swing.JButton botonPonerMagiaSinUsar;
    private javax.swing.JButton botonPonerMagiaUsandola;
    private javax.swing.JButton botonPonerMonstruo;
    private javax.swing.JButton botonPonerMonstruoEnAtaque;
    private javax.swing.JButton botonPonerMonstruoEnDefensa;
    private javax.swing.JButton botonPonerTrampa;
    private javax.swing.JButton botonSaltarBattlePhase;
    private javax.swing.JButton botonSaltarMainPhase1;
    private javax.swing.JButton botonSaltarMainPhase2;
    private javax.swing.JButton botonTerminarBattlePhase;
    private javax.swing.JButton botonTerminarMainPhase1;
    private javax.swing.JButton botonTerminarMainPhase2;
    private javax.swing.JButton botonVolverAJugar;
    private javax.swing.JPanel cardDesarrollo;
    private javax.swing.JPanel cardFinal;
    private javax.swing.JPanel cardInicio;
    private javax.swing.JPanel contenedorDeCards;
    private javax.swing.JLabel etiquetaCementerio;
    private javax.swing.JLabel etiquetaDeInputMultifuncion;
    private javax.swing.JLabel etiquetaDivisoraDelCampo;
    private javax.swing.JLabel etiquetaFaseEnCurso;
    private javax.swing.JLabel etiquetaHasGanado;
    private javax.swing.JLabel etiquetaJugador1;
    private javax.swing.JLabel etiquetaJugador1EnCampo;
    private javax.swing.JLabel etiquetaJugador2;
    private javax.swing.JLabel etiquetaJugador2EnCampo;
    private javax.swing.JLabel etiquetaMano;
    private javax.swing.JLabel etiquetaMultifuncion;
    private javax.swing.JLabel etiquetaTurnoEnCurso;
    private javax.swing.JLabel fondoDesarrollo;
    private javax.swing.JLabel fondoFinal;
    private javax.swing.JLabel fondoInicio;
    private javax.swing.JTextField ingresoNombreJugador1;
    private javax.swing.JTextField ingresoNombreJugador2;
    private javax.swing.JTextField inputMultifuncion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JLabel magiaOTrampa0Jugador1EnCampo;
    private javax.swing.JLabel magiaOTrampa0Jugador2EnCampo;
    private javax.swing.JLabel magiaOTrampa1Jugador1EnCampo;
    private javax.swing.JLabel magiaOTrampa1Jugador2EnCampo;
    private javax.swing.JLabel magiaOTrampa2Jugador1EnCampo;
    private javax.swing.JLabel magiaOTrampa2Jugador2EnCampo;
    private javax.swing.JLabel magiaOTrampa3Jugador1EnCampo;
    private javax.swing.JLabel magiaOTrampa3Jugador2EnCampo;
    private javax.swing.JLabel magiaOTrampa4Jugador1EnCampo;
    private javax.swing.JLabel magiaOTrampa4Jugador2EnCampo;
    private javax.swing.JLabel monstruo0Jugador1EnCampo;
    private javax.swing.JLabel monstruo0Jugador2EnCampo;
    private javax.swing.JLabel monstruo1Jugador1EnCampo;
    private javax.swing.JLabel monstruo1Jugador2EnCampo;
    private javax.swing.JLabel monstruo2Jugador1EnCampo;
    private javax.swing.JLabel monstruo2Jugador2EnCampo;
    private javax.swing.JLabel monstruo3Jugador1EnCampo;
    private javax.swing.JLabel monstruo3Jugador2EnCampo;
    private javax.swing.JLabel monstruo4Jugador1EnCampo;
    private javax.swing.JLabel monstruo4Jugador2EnCampo;
    private javax.swing.JScrollPane scrollCementerio;
    private javax.swing.JScrollPane scrollMano;
    private javax.swing.JTable tablaCementerio;
    private javax.swing.JTable tablaMano;
    // End of variables declaration//GEN-END:variables
}
